### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by quatoo** [TestEssence/feature-to-md#1]
This lib is very useful for my test team to document the BDD, but I miss some features like, 

- **A clear way to set MDs destination folder**. I try `dest` parameter but seems to be the destination FILE name
- **Recursive input directory not working**. Although it is described in the readme, it seems that the recursive format was not implemented. It works, but for one file at a time 😫 

How can I contribute to implement this features?

**Comment by anatolysakhno** [comment]
Hey @quatoo,
yes, this package is not tested well yet. I have added you to the project so please go ahead and create pull requests. 
Thank you for your input.
